---
- name: Create Azure VM
  hosts: localhost
  connection: local
  vars_prompt:
    - name: password
      prompt: "Enter local administrator password"

  vars: 
    - resource_group_name : devops-interview-gauntlet-x-skrishna

  tasks:

  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{resource_group_name}}"
      name: vNet
      address_prefixes: "10.0.0.0/16"

  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{resource_group_name}}"
      name: subnet
      address_prefix: "10.0.1.0/24"
      virtual_network: vNet

  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{resource_group_name}}"
      allocation_method: Static
      name: pip1
    register: output_ip_address

  - name: Output public IP
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}"




  - name: Create Network Security Group
    azure_rm_securitygroup:
      resource_group: "{{resource_group_name}}"
      name: networkSecurityGroup
      rules:
        - name: 'allow_rdp'
          protocol: Tcp
          destination_port_range: 3389
          access: Allow
          priority: 1001
          direction: Inbound
        - name: 'allow_web_traffic'
          protocol: Tcp
          destination_port_range:
            - 80
          access: Allow
          priority: 1002
          direction: Inbound

  - name: Create a network interface 1
    azure_rm_networkinterface:
      name: nic1
      resource_group: "{{resource_group_name}}"
      virtual_network: vNet
      subnet_name: subnet
      security_group: networkSecurityGroup
      ip_configurations:
        - name: default
          public_ip_address_name: pip1
          primary: True

  - name: Create VM 1
    azure_rm_virtualmachine:
      resource_group: "{{resource_group_name}}"
      name: winvm1
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      admin_password: "{{ password }}"
      network_interfaces: nic1
      os_type: Windows
      image:
          offer: WindowsServer
          publisher: MicrosoftWindowsServer
          sku: 2019-Datacenter
          version: latest
    no_log: true

  - name: Enable IIS in the VM 1
    azure_rm_virtualmachineextension:
      name: winrmextension1
      resource_group: "{{resource_group_name}}"
      virtual_machine_name: winvm1
      publisher: Microsoft.Compute
      virtual_machine_extension_type: CustomScriptExtension
      type_handler_version: '1.9'
      settings: '{"commandToExecute": "powershell Add-WindowsFeature Web-Server"}'
      auto_upgrade_minor_version: true


  - name: Create public IP address 2
    azure_rm_publicipaddress:
      resource_group: "{{resource_group_name}}"
      allocation_method: Static
      name: pip2
    register: output_ip_address2

  - name: Output public IP
    debug:
      msg: "The public IP 2 is {{ output_ip_address2.state.ip_address }}"


  - name: Create a network interface 2
    azure_rm_networkinterface:
      name: nic2
      resource_group: "{{resource_group_name}}"
      virtual_network: vNet
      subnet_name: subnet
      security_group: networkSecurityGroup
      ip_configurations:
        - name: default
          public_ip_address_name: pip2
          primary: True


  - name: Create VM 2
    azure_rm_virtualmachine:
      resource_group: "{{resource_group_name}}"
      name: winvm2
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      admin_password: "{{ password }}"
      network_interfaces: nic2
      os_type: Windows
      image:
          offer: WindowsServer
          publisher: MicrosoftWindowsServer
          sku: 2019-Datacenter
          version: latest
    no_log: true



  - name: Enable IIS in the VM 2
    azure_rm_virtualmachineextension:
      name: winrmextension2
      resource_group: "{{resource_group_name}}"
      virtual_machine_name: winvm2
      publisher: Microsoft.Compute
      virtual_machine_extension_type: CustomScriptExtension
      type_handler_version: '1.9'
      settings: '{"commandToExecute": "powershell Add-WindowsFeature Web-Server"}'
      auto_upgrade_minor_version: true

